name: rebuild-protos

on: 
  workflow_dispatch:
  # push:

jobs:
  multi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout lnd-grpc-client
        uses: actions/checkout@v3
        with:
          path: lnd-grpc-client

      - name: Checkout LND
        uses: actions/checkout@v3
        with:
          repository: "lightningnetwork/lnd"
          ref: "v0.16.0-beta.rc2"
          path: lnd

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install Deps
        working-directory: ./lnd-grpc-client
        run: |
          poetry install


      - name: Rebuild the Protos
        run: |
            export CLIENT_DIR=$(readlink -f lnd-grpc-client)
            export APP_DIR=$(readlink -f lnd)
            cd lnd-grpc-client
            source .venv/bin/activate
            python3 $CLIENT_DIR/rebuild_protos.py
            git status

